//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.MapObjects.SpectrumMapObject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITS.MapObjects.SpectrumMapObject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advertisement_0 {
            get {
                object obj = ResourceManager.GetObject("Advertisement_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advertisement_1 {
            get {
                object obj = ResourceManager.GetObject("Advertisement_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advertisement_2 {
            get {
                object obj = ResourceManager.GetObject("Advertisement_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advertisement_3 {
            get {
                object obj = ResourceManager.GetObject("Advertisement_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advertisement_4 {
            get {
                object obj = ResourceManager.GetObject("Advertisement_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
       
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dinner {
            get {
                object obj = ResourceManager.GetObject("dinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditAdvertisementImageSource {
            get {
                object obj = ResourceManager.GetObject("EditAdvertisementImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fax {
            get {
                object obj = ResourceManager.GetObject("fax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icq {
            get {
                object obj = ResourceManager.GetObject("icq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itsgisWND_BG_11 {
            get {
                object obj = ResourceManager.GetObject("itsgisWND_BG_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itsgisWND_BottomButton {
            get {
                object obj = ResourceManager.GetObject("itsgisWND_BottomButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
       
 
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrganizationInformationImageSource1 {
            get {
                object obj = ResourceManager.GetObject("OrganizationInformationImageSource1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phone {
            get {
                object obj = ResourceManager.GetObject("phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение изменений.
        /// </summary>
        internal static string PluginBaseAcceptGroupName {
            get {
                return ResourceManager.GetString("PluginBaseAcceptGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseAcceptImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseAcceptImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить изменения.
        /// </summary>
        internal static string PluginBaseAcceptUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseAcceptUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseAddLineObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseAddLineObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить линейный объект.
        /// </summary>
        internal static string PluginBaseAddLineObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseAddLineObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseAddPointObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseAddPointObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить точечный объект.
        /// </summary>
        internal static string PluginBaseAddPointObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseAddPointObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseAddPolygonObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseAddPolygonObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить полигональный объект.
        /// </summary>
        internal static string PluginBaseAddPolygonObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseAddPolygonObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История изменений.
        /// </summary>
        internal static string PluginBaseBackGroupName {
            get {
                return ResourceManager.GetString("PluginBaseBackGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseBackImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseBackImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string PluginBaseBackUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseBackUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение изменений.
        /// </summary>
        internal static string PluginBaseCancelGroupName {
            get {
                return ResourceManager.GetString("PluginBaseCancelGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseCancelImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseCancelImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить изменения.
        /// </summary>
        internal static string PluginBaseCancelUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseCancelUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseCopyPasteVeloObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseCopyPasteVeloObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать .
        /// </summary>
        internal static string PluginBaseCopyPasteVeloObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseCopyPasteVeloObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseDeleteObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseDeleteObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseDeleteVeloObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseDeleteVeloObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить .
        /// </summary>
        internal static string PluginBaseDeleteVeloObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseDeleteVeloObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseEditGeometryVeloObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseEditGeometryVeloObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать геометрию.
        /// </summary>
        internal static string PluginBaseEditGeometryVeloObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseEditGeometryVeloObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string PluginBaseEditVeloObjectGroupName {
            get {
                return ResourceManager.GetString("PluginBaseEditVeloObjectGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseEditVeloObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseEditVeloObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать семантику объекта.
        /// </summary>
        internal static string PluginBaseEditVeloObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseEditVeloObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История изменений.
        /// </summary>
        internal static string PluginBaseForwardGroupName {
            get {
                return ResourceManager.GetString("PluginBaseForwardGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseForwardImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseForwardImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вперёд.
        /// </summary>
        internal static string PluginBaseForwardUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseForwardUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseRotateGeometryImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseRotateGeometryImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повернуть геометрию.
        /// </summary>
        internal static string PluginBaseRotateGeometryUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseRotateGeometryUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSearchVeloObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseSearchVeloObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск .
        /// </summary>
        internal static string PluginBaseSearchVeloObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSearchVeloObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectDismantleGroupName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectDismantleGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонтировать.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectDismantleShortUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectDismantleShortUserFunctionalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный
        /// </summary>
        internal static string PluginBaseSelectVeloObjectMobileShortUserFunctionalName
        {
            get
            {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectMobileShortUserFunctionalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Праздничный
        /// </summary>
        internal static string PluginBaseSelectVeloObjectCelebrateShortUserFunctionalName
        {
            get
            {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectCelebrateShortUserFunctionalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSelectVeloObjectDismantleSmallImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseSelectVeloObjectDismantleSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSelectVeloObjectMobileSmallImageSource
        {
            get
            {
                object obj = ResourceManager.GetObject("PluginBaseSelectVeloObjectMobileSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить подлежащие демонтированию.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectDismantleUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectDismantleUserFunctionalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить мобильные.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectMobileUserFunctionalName
        {
            get
            {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectMobileUserFunctionalName", resourceCulture);
            }
        }


        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить праздничные.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectCelebrateUserFunctionalName
        {
            get
            {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectCelebrateUserFunctionalName", resourceCulture);
            }
        }


        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSelectVeloObjectImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseSelectVeloObjectImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectRequiredGroupName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectRequiredGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectMobileGroupName
        {
            get
            {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectMobileGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Требуются.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectRequiredShortUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectRequiredShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSelectVeloObjectRequiredSmallImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseSelectVeloObjectRequiredSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить требуемые .
        /// </summary>
        internal static string PluginBaseSelectVeloObjectRequiredUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectRequiredUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectSetGroupName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectSetGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установленные.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectSetShortUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectSetShortUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSelectVeloObjectSetSmallImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseSelectVeloObjectSetSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить установленные.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectSetUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectSetUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        internal static string PluginBaseSelectVeloObjectUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSelectVeloObjectUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string PluginBaseVeloObjectInfoGroupName {
            get {
                return ResourceManager.GetString("PluginBaseVeloObjectInfoGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseVeloObjectInfoImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseVeloObjectInfoImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о велопарковке.
        /// </summary>
        internal static string PluginBaseVeloObjectInfoUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseVeloObjectInfoUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомости.
        /// </summary>
        internal static string PluginBaseSummaryGroupName {
            get {
                return ResourceManager.GetString("PluginBaseSummaryGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSummaryImageSource {
            get {
                object obj = ResourceManager.GetObject("PluginBaseSummaryImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сводная ведомость.
        /// </summary>
        internal static string PluginBaseSummaryUserFunctionalName {
            get {
                return ResourceManager.GetString("PluginBaseSummaryUserFunctionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты.
        /// </summary>
        internal static string PluginBaseToolsGroupName {
            get {
                return ResourceManager.GetString("PluginBaseToolsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название плагина.
        /// </summary>
        internal static string PluginToolName {
            get {
                return ResourceManager.GetString("PluginToolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchOrganizationImageSource {
            get {
                object obj = ResourceManager.GetObject("SearchOrganizationImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap site {
            get {
                object obj = ResourceManager.GetObject("site", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skype {
            get {
                object obj = ResourceManager.GetObject("skype", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VeloObjectInformationImageSource1 {
            get {
                object obj = ResourceManager.GetObject("VeloObjectInformationImageSource1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слой плагина плагинов.
        /// </summary>
        internal static string VeloObjectLayerAlias {
            get {
                return ResourceManager.GetString("VeloObjectLayerAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap time {
            get {
                object obj = ResourceManager.GetObject("time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d1
        {
            get
            {
                object obj = ResourceManager.GetObject("d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d2
        {
            get
            {
                object obj = ResourceManager.GetObject("d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d3
        {
            get
            {
                object obj = ResourceManager.GetObject("d3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d4
        {
            get
            {
                object obj = ResourceManager.GetObject("d4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d5
        {
            get
            {
                object obj = ResourceManager.GetObject("d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d6
        {
            get
            {
                object obj = ResourceManager.GetObject("d6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d7
        {
            get
            {
                object obj = ResourceManager.GetObject("d7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d8
        {
            get
            {
                object obj = ResourceManager.GetObject("d8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap none1
        {
            get
            {
                object obj = ResourceManager.GetObject("none1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k1
        {
            get
            {
                object obj = ResourceManager.GetObject("k1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k2
        {
            get
            {
                object obj = ResourceManager.GetObject("k2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k3
        {
            get
            {
                object obj = ResourceManager.GetObject("k3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k4
        {
            get
            {
                object obj = ResourceManager.GetObject("k4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k5
        {
            get
            {
                object obj = ResourceManager.GetObject("k5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k6
        {
            get
            {
                object obj = ResourceManager.GetObject("k6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k7
        {
            get
            {
                object obj = ResourceManager.GetObject("k7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap k8
        {
            get
            {
                object obj = ResourceManager.GetObject("k8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n1
        {
            get
            {
                object obj = ResourceManager.GetObject("n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n2
        {
            get
            {
                object obj = ResourceManager.GetObject("n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n3
        {
            get
            {
                object obj = ResourceManager.GetObject("n3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n4
        {
            get
            {
                object obj = ResourceManager.GetObject("n4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n5
        {
            get
            {
                object obj = ResourceManager.GetObject("n5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n6
        {
            get
            {
                object obj = ResourceManager.GetObject("n6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n7
        {
            get
            {
                object obj = ResourceManager.GetObject("n7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap n8
        {
            get
            {
                object obj = ResourceManager.GetObject("n8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap knone
        {
            get
            {
                object obj = ResourceManager.GetObject("knone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dnone
        {
            get
            {
                object obj = ResourceManager.GetObject("dnone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PluginBaseSelectVeloObjectCelebrateSmallImageSource
        {
            get
            {
                object obj = ResourceManager.GetObject("PluginBaseSelectVeloObjectCelebrateSmallImageSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


    }
}
