INSERT INTO info_category (id, name, parent_id, key_words) VALUES (1, 'Оборудование / Инструмент', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (2, 'Стеллажи / Витрины', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (3, 'Ремонт промышленного оборудования', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (4, 'Резинотехнические изделия', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (5, 'Оборудование для сельского хозяйства', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (6, 'Оборудование для автоматизации промышленных предприятий', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (7, 'Малярный инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (8, 'Котельное оборудование / Котлы', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (9, 'Деревообрабатывающий инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (10, 'Буровое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (11, 'Звуковое / световое / видеооборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (12, 'Абразивный инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (13, 'Электроинструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (14, 'Подшипники', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (15, 'Оборудование для лабораторий', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (16, 'Деревообрабатывающее оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (17, 'Газовое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (18, 'Торгово-выставочное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (19, 'Оборудование для автоматизации торговли', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (20, 'Кондиционеры', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (21, 'Банковское оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (22, 'Швейное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (23, 'Прокат мультимедийного / презентационного оборудования', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (24, 'Оборудование для нанесения полимерных покрытий', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (25, 'Металлорежущий инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (26, 'Проекционное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (27, 'Очистители воздуха', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (28, 'Оборудование для производства мебели', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (29, 'Вендинговое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (30, 'Бензоинструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (31, 'Продажа / установка теплых полов', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (32, 'Продажа платежных терминалов', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (33, 'Пресс-формы / Штампы', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (34, 'Оборудование для предприятий общественного питания', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (35, 'Нефтегазовое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (36, 'Заточка / шлифовка режущих инструментов', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (37, 'Продажа инфракрасных кабин', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (38, 'Лингафонное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (39, 'Клининговое оборудование / инвентарь', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (40, 'ККМ / Расходные материалы', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (41, 'Измерительный инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (42, 'Игорное оборудование / Аксессуары', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (43, 'Техника для склада', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (44, 'Слесарно-монтажный инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (45, 'Сварочное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (46, 'Оборудование для пищевого производства', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (47, 'Оборудование для автосервиса', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (48, 'Горно-шахтное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (49, 'Бензиновое / дизельное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (50, 'Тепловентиляционное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (51, 'Ремонт электроинструмента', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (52, 'Полиграфическое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (53, 'Пневмоинструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (54, 'Пневматическое / компрессорное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (55, 'Оборудование для салонов красоты', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (56, 'Оборудование для АЗС и нефтебаз', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (57, 'Оборудование для автомоек', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (58, 'Металлообрабатывающее оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (59, 'Каркасно-тентовые конструкции', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (60, 'Весовое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (61, 'Абразивоструйное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (62, 'Холодильное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (63, 'Ткацкое оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (64, 'Оборудование для энергосбережения', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (65, 'Насосное оборудование', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (66, 'Гидравлическое оборудование / инструмент', 1, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (67, 'Автосервис / Автотовары', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (68, 'Тюнинг', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (69, 'Тонировочные / защитные пленки для автомобилей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (70, 'Специализированное автооборудование', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (71, 'Развал / Схождение', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (72, 'Запчасти к сельхозтехнике', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (73, 'Аппаратная замена масла', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (74, 'Автохимия / Масла', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (75, 'Автомобильные аккумуляторы', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (76, 'Автозапчасти для иномарок', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (77, 'Ремонт спецавтотехники', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (78, 'Контрактные автозапчасти', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (79, 'Автостекло', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (80, 'Авторемонт и техобслуживание (СТО )', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (81, 'Автозвук - продажа / установка', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (82, 'Ремонт дизельных двигателей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (83, 'Автомойки', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (84, 'Ремонт электронных систем управления автомобиля', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (85, 'Ремонт грузовых автомобилей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (86, 'Кузовной ремонт', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (87, 'Ремонт бензиновых двигателей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (88, 'Газовое оборудование для автотранспорта', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (89, 'Антикоррозийная обработка автомобилей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (90, 'Автошины / Диски', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (91, 'Автозапчасти для грузовых автомобилей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (92, 'Шиномонтаж', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (93, 'Ремонт ходовой части автомобиля', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (94, 'Ремонт / заправка автокондиционеров', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (95, 'Запчасти для общественного транспорта', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (96, 'Ремонт топливной аппаратуры дизельных двигателей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (97, 'Ремонт карбюраторов / инжекторов', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (98, 'Автостоянки', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (99, 'Автозапчасти для отечественных автомобилей', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (100, 'Автозаправочные станции (АЗС)', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (101, 'Автоаксессуары', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (102, 'Хранение шин', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (103, 'Тонирование автостекол', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (104, 'Ремонт автоэлектрики', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (105, 'Автоэмали', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (106, 'Авторазборы', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (107, 'Ремонт мототехники', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (108, 'Ремонт АКПП', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (109, 'Пункты технического осмотра транспорта', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (110, 'Установка / ремонт автостекол', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (111, 'Запчасти для спецавтотехники', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (112, 'Автосигнализации - продажа / установка', 67, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (113, 'Медицина / Здоровье / Красота', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (114, 'Стоматологическое оборудование / материалы', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (115, 'Услуги трихолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (116, 'Медицинские лаборатории', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (117, 'Лечение ЛОР-заболеваний', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (118, 'Услуги дерматовенеролога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (119, 'Стоматологические поликлиники', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (120, 'Услуги гинеколога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (121, 'Лекарственные препараты', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (122, 'Поликлиники взрослые', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (123, 'Услуги логопеда', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (124, 'Средства гигиены', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (125, 'Фитоцентры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (126, 'Бюро медико-социальной экспертизы', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (127, 'Травмпункты', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (128, 'Лечение зависимостей', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (129, 'Поликлиники детские', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (130, 'Студии загара', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (131, 'Патронажные услуги', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (132, 'Услуги гастроэнтеролога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (133, 'Аптеки', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (134, 'Диспансеры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (135, 'Ногтевые студии', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (136, 'Госпитали', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (137, 'Диагностические центры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (138, 'Медицинское оборудование / инструмент', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (139, 'Тонизирующие процедуры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (140, 'Многопрофильные медицинские центры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (141, 'Гирудотерапия', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (142, 'Протезные / ортопедические изделия', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (143, 'Услуги кардиолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (144, 'Оптика', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (145, 'Медицинские расходные материалы', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (146, 'Центры планирования семьи', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (147, 'Станции переливания крови', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (148, 'Пластическая хирургия', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (149, 'Косметика / расходные материалы для салонов красоты', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (150, 'Санатории / Профилактории', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (151, 'Услуги врача-гомеопата', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (152, 'Женские консультации', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (153, 'Мануальная терапия', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (154, 'Родильные дома', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (155, 'Центры борьбы со СПИДом', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (156, 'Услуги массажиста', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (157, 'Изготовление лекарственных препаратов на заказ', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (158, 'Медицинские приборы / аппараты', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (159, 'Ортопедия и травматология', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (160, 'Услуги аллерголога / иммунолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (161, 'Стоматологические центры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (162, 'Косметические салоны', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (163, 'Услуги уролога / андролога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (164, 'Больницы', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (165, 'Парикмахерские', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (166, 'Услуги невролога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (167, 'Услуги детских специалистов', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (168, 'Коррекция зрения / Лечение офтальмологических заболеваний', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (169, 'Фельдшерско-акушерские пункты', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (170, 'Медицинские комиссии', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (171, 'Услуги маммолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (172, 'Косметика / Парфюмерия', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (173, 'Санитарно-эпидемиологический надзор', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (174, 'Биологически активные добавки (БАД)', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (175, 'Услуги проктолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (176, 'Услуги психолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (177, 'Школы для будущих мам', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (178, 'Очищение организма', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (179, 'Реабилитационные центры', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (180, 'Услуги эндокринолога', 113, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (181, 'Юридические / финансовые / бизнес-услуги', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (182, 'Юридическое обслуживание', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (183, 'Оформление недвижимости / земли', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (184, 'Организация выставок', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (185, 'Лизинговые услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (186, 'Ипотека / Жилищное кредитование', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (187, 'Экологическая оценка', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (188, 'Управленческий консалтинг', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (189, 'Регистрация / ликвидация предприятий', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (190, 'Нотариальные услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (191, 'Микрофинансирование', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (192, 'Ломбарды', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (193, 'Аудиторские услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (194, 'Регистрация ценных бумаг', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (195, 'Операции на фондовом рынке', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (196, 'Миграционные услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (197, 'Коллекторские услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (198, 'Бухгалтерские услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (199, 'Помощь в оформлении ипотеки', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (200, 'Выгодные покупки с 2ГИС', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (201, 'Лицензирование', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (202, 'Ведение дел в судах', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (203, 'Банки', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (204, 'Экспертиза промышленной безопасности', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (205, 'Эквайринг', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (206, 'Таможенное оформление', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (207, 'Услуги факторинга', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (208, 'Помощь в оформлении кредита', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (209, 'Паевые инвестиционные фонды (ПИФы)', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (210, 'Автокредитование', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (211, 'Экспертиза товаров народного потребления', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (212, 'Финансовый консалтинг', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (213, 'Патентные услуги', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (214, 'Оценка собственности', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (215, 'Кредитные потребительские кооперативы граждан', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (216, 'Инвестиционные компании', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (217, 'Дилинговые центры', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (218, 'Банкоматы', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (219, 'Страхование', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (220, 'Сертификация', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (221, 'Изготовление печатей / штампов', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (222, 'Саморегулируемые организации (СРО )', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (223, 'Оформление виз', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (224, 'Негосударственные пенсионные фонды', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (225, 'Кассы обмена валют', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (226, 'Защита авторских прав', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (227, 'Энергоаудит', 181, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (228, 'Хозтовары / Канцелярия / Упаковка', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (229, 'Календари / Открытки - опт', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (230, 'Бытовая химия', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (231, 'Бумажная упаковка', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (232, 'Хозяйственные товары', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (233, 'Семена / Посадочный материал', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (234, 'Садово-огородный инвентарь / техника', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (235, 'Стеклянная тара', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (236, 'Книги', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (237, 'Укрывной материал', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (238, 'Упаковочные материалы', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (239, 'Посуда', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (240, 'Гофротара', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (241, 'Пакеты / Пленки', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (242, 'Канцелярские товары', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (243, 'Изготовление / продажа теплиц', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (244, 'Учебная литература', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (245, 'Средства защиты растений / Удобрения', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (246, 'Подарочная упаковка', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (247, 'Пластиковая тара', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (248, 'Одноразовая посуда', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (249, 'Фасовочно-упаковочное оборудование', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (250, 'Офисная бумага', 228, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (251, 'Транспорт / Грузоперевозки', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (252, 'Прокат автотранспорта', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (253, 'Авиагрузоперевозки', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (254, 'Строительство / ремонт железных дорог', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (255, 'Железнодорожные вокзалы и станции', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (256, 'Экспедирование грузов', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (257, 'Трамвайные депо', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (258, 'Продажа транспортных карт', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (259, 'Междугородные автогрузоперевозки', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (260, 'Железнодорожное оборудование / техника', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (261, 'Экспресс-почта', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (262, 'Пассажирские автотранспортные предприятия (ПАТП)', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (263, 'Вывоз мусора / снега', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (264, 'Услуги грузчиков', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (265, 'Мототехника', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (266, 'Автовокзал', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (267, 'Авиакомпании', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (268, 'Сельхозтехника', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (269, 'Международные грузоперевозки', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (270, 'Заказ строительной / спецавтотехники', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (271, 'Заказ пассажирского легкового транспорта', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (272, 'Железнодорожные грузоперевозки', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (273, 'Авиабилеты', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (274, 'Услуги складского хранения', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (275, 'Троллейбусные депо', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (276, 'Продажа легковых автомобилей', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (277, 'Аэропорты', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (278, 'Спецавтотехника', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (279, 'Оформление купли-продажи автомобилей', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (280, 'Морские / речные грузоперевозки', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (281, 'Заказ автобусов', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (282, 'Железнодорожные билеты', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (283, 'Автоэкспертиза', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (284, 'Специализированные дорожные средства / устройства', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (285, 'Речной вокзал', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (286, 'Городские автогрузоперевозки', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (287, 'Продажа грузовых автомобилей', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (288, 'Продажа автобусов', 251, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (289, 'Товары для животных / Ветеринария', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (290, 'Комбикорм / Кормовые добавки', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (291, 'Клубы домашних животных / Питомники', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (292, 'Зоотовары', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (293, 'Ветеринарные аптеки', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (294, 'Услуги по уходу за животными', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (295, 'Гостиницы для животных', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (296, 'Аквариумы', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (297, 'Ветеринарные препараты', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (298, 'Ветеринарные клиники', 289, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (299, 'Досуг / Развлечения / Общественное питание', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (300, 'Продажа лотерейных билетов', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (301, 'Цирк', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (302, 'Суши-бары / рестораны', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (303, 'Столовые', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (304, 'Кафе-кондитерские / Кофейни', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (305, 'Бары', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (306, 'Организация театральных / концертных мероприятий', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (307, 'Бильярдные залы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (308, 'Кейтеринг', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (309, 'Зоопарк', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (310, 'Детские игротеки', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (311, 'Букмекерские конторы / Лотереи', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (312, 'Аквапарки / Водные аттракционы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (313, 'Доставка готовых блюд', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (314, 'Бани / Сауны', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (315, 'Услуги праздничного оформления', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (316, 'Рестораны', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (317, 'Кулинария', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (318, 'Кафе', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (319, 'Залы детских игровых автоматов', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (320, 'Детские / подростковые клубы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (321, 'Кафе / рестораны быстрого питания', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (322, 'Ботанический сад', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (323, 'Банкетные залы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (324, 'Стрелковые клубы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (325, 'Салюты', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (326, 'Боулинг', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (327, 'Спортивно-тактические клубы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (328, 'Парки культуры и отдыха', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (329, 'Организация экскурсий по городу', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (330, 'Ночные клубы', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (331, 'Кинотеатры', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (332, 'Дома / дворцы культуры', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (333, 'Дайвинг-центры', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (334, 'Организация и проведение праздников', 299, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (335, 'Спорт / Отдых / Туризм', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (336, 'Центры йоги', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (337, 'Спортивные секции', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (338, 'Спортивное оборудование', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (339, 'Прокат спортивного инвентаря', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (340, 'Лыжные базы / Горнолыжные комплексы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (341, 'Картинг- / мотоцентры', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (342, 'Детские лагеря', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (343, 'Федерации спорта', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (344, 'Спортивные клубы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (345, 'Спортивное питание', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (346, 'Квартирные бюро', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (347, 'Фитнес-клубы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (348, 'Бассейны', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (349, 'Стадионы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (350, 'Спортивно-интеллектуальные клубы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (351, 'Снаряжение для туризма и отдыха', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (352, 'Туроператоры', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (353, 'Туристические агентства', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (354, 'Спортивные школы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (355, 'Гольф-клубы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (356, 'Спортивный инвентарь', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (357, 'Спортивная одежда / обувь', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (358, 'Ледовые дворцы / Катки', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (359, 'Базы отдыха', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (360, 'Спортивно-технические клубы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (361, 'Конные клубы / Ипподромы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (362, 'Ремонт велосипедов', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (363, 'Игровое оборудование', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (364, 'Гостиницы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (365, 'Танцевальные школы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (366, 'Авиационные клубы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (367, 'Тренажерные залы', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (368, 'Рыболовные принадлежности', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (369, 'Охотничьи принадлежности / Оружие', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (370, 'Лодки / Катера', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (371, 'Велосипеды', 335, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (372, 'Реклама / Полиграфия / СМИ', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (373, 'Широкоформатная печать / УФ-печать', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (374, 'Термопечать', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (375, 'Размещение наружной рекламы', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (376, 'Производство пластиковых карт', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (377, 'Модельные агентства', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (378, 'Киоски по продаже печатной продукции', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (379, 'PR / Связи с общественностью', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (380, 'Флексопечать', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (381, 'Полиграфические услуги', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (382, 'Indoor-реклама (реклама в помещениях)', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (383, 'Фотостудии', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (384, 'Студии звукозаписи', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (385, 'Размещение рекламы в СМИ', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (386, 'Маркетинговые / социологические исследования', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (387, 'Шелкография', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (388, 'Услуги гравировки', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (389, 'Расходные материалы для полиграфии', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (390, 'Размещение рекламы на транспорте', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (391, 'Офсетная печать', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (392, 'Оперативная полиграфия', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (393, 'Газеты', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (394, 'Рекламные агентства полного цикла', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (395, 'Изготовление бизнес-сувениров', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (396, 'Журналы', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (397, 'Директ-мэйл', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (398, 'Справочники', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (399, 'Организация и проведение промоушн-акций', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (400, 'Бумага для полиграфии', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (401, 'Предпечатная подготовка', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (402, 'Изготовление рекламных конструкций', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (403, 'Тампопечать', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (404, 'Материалы для наружной рекламы', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (405, 'Дизайн рекламы', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (406, 'Телевидение', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (407, 'Радиостанции', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (408, 'Послепечатная обработка', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (409, 'Световая реклама', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (410, 'Видеостудии', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (411, 'Агентства по подписке печатных изданий', 372, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (412, 'Коммунальные / бытовые / ритуальные услуги', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (413, 'Фото на документы', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (414, 'Ремонт часов', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (415, 'Службы знакомств', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (416, 'Благоустройство улиц', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (417, 'Ателье меховые / кожаные', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (418, 'Химчистки одежды / текстиля', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (419, 'ТСЖ', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (420, 'Профессиональная уборка', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (421, 'Помощь в организации похорон', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (422, 'Изготовление ключей', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (423, 'Фотоцентры', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (424, 'Пункты приема платежей / Расчетные центры коммунальных услуг', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (425, 'ЖЭУ', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (426, 'Ателье трикотажные', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (427, 'Дезинфекция / Дератизация / Дезинсекция', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (428, 'Чистка / реставрация пухо-перьевых изделий', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (429, 'Памятники / Ритуальные принадлежности', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (430, 'Общежития', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (431, 'Кладбища', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (432, 'Прачечные', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (433, 'Ателье швейные', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (434, 'Техобслуживание теплоэнергосетей', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (435, 'Теплоэнергоснабжение / ТЭЦ', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (436, 'Домашний персонал', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (437, 'Продажа / обслуживание подъемно-пассажирских устройств', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (438, 'ЖКХ', 412, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (439, 'Строительство / Недвижимость / Ремонт', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (440, 'Строительство мостов / тоннелей / путепроводов', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (441, 'Строительство и монтаж бассейнов / фонтанов', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (442, 'Строительство гаражей', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (443, 'Строительное оборудование', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (444, 'Монтаж систем отопления / водоснабжения / канализации', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (445, 'Геофизические работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (446, 'Геологические работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (447, 'Взрывные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (448, 'Строительство систем газоснабжения', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (449, 'Строительство / ремонт наружных инженерных сетей', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (450, 'Строительство административных зданий', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (451, 'Деревообработка', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (452, 'Быстровозводимые здания / сооружения', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (453, 'Строительство / ремонт дорог', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (454, 'Сантехника / Санфаянс', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (455, 'Промышленное строительство', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (456, 'Архитектурно-строительное проектирование', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (457, 'Автоматизация инженерных систем', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (458, 'Остекление балконов / лоджий', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (459, 'Монтаж климатических систем', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (460, 'Геодезические работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (461, 'Услуги по устройству промышленных / наливных полов', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (462, 'Тонирование стекол зданий / конструкций', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (463, 'Техническая экспертиза зданий и сооружений', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (464, 'Теплоизоляционные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (465, 'Строительство дач / коттеджей', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (466, 'Строительство бань / саун', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (467, 'Реконструкция и капремонт зданий', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (468, 'Буровые работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (469, 'Согласование перепланировок', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (470, 'Сварочные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (472, 'Гидромассажное оборудование', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (473, 'Бюро технической инвентаризации (БТИ)', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (474, 'Электромонтажные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (475, 'Снос зданий / сооружений', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (476, 'Продажа / аренда недвижимости за рубежом', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (477, 'Новостройки', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (478, 'Земельно-кадастровые работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (479, 'Жилищное строительство', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (480, 'Бизнес-центры', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (481, 'Антикоррозийная обработка металлоконструкций', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (482, 'Агентства недвижимости', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (483, 'Строительная техника', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (484, 'Сервисное обслуживание бассейнов', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (485, 'Оборудование для очистки воды', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (486, 'Ландшафтная архитектура', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (487, 'Дизайн интерьеров', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (488, 'Полимерная порошковая окраска', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (489, 'Инжиниринговые услуги', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (490, 'Земляные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (491, 'Аренда помещений', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (492, 'Строительные леса / Вышки-туры', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (493, 'Системы отопления / водоснабжения / канализации', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (494, 'Проектирование инженерных систем', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (495, 'Кровельные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (496, 'Высотные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (497, 'Фасадные работы', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (498, 'Строительство АЗС / АГЗС', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (499, 'Ремонт / отделка помещений', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (500, 'Алмазное бурение / резка', 439, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (501, 'Аварийные / справочные / экстренные службы', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (502, 'Управление ГО и ЧС', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (503, 'Скорая медицинская помощь', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (504, 'Справочно-информационные услуги', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (505, 'Службы экстренного вызова', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (506, 'Пожарная охрана', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (507, 'Телефоны доверия', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (508, 'Аварийные службы', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (509, 'Службы спасения', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (510, 'Независимые службы аварийных комиссаров', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (511, 'Эвакуация автомобилей', 501, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (512, 'Торговые комплексы / Спецмагазины', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (513, 'Торговые центры', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (514, 'Эротические товары', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (515, 'Цветы', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (517, 'Комиссионные магазины', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (518, 'Сувениры / Подарки', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (519, 'Рынки', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (520, 'Универсальные магазины / комплексы', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (521, 'Товары для творчества и рукоделия', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (522, 'Ювелирные изделия', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (523, 'Ремонт / изготовление ювелирных изделий', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (524, 'Часы', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (525, 'Супермаркеты', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (526, 'Продажа купонов со скидками / Дисконтные системы', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (527, 'Гипермаркеты', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (528, 'Новогодние товары', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (529, 'Аксессуары для бань и саун', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (530, 'Торгово-развлекательные центры / Моллы', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (531, 'Интернет-магазины', 512, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (532, 'Охрана / Безопасность', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (533, 'Спасательное оборудование', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (534, 'Продажа / установка домофонов', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (535, 'Монтаж охранно-пожарных систем', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (536, 'Детективные услуги', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (537, 'Противопожарное оборудование / инвентарь', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (538, 'Услуги охраны', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (539, 'Огнезащитная обработка', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (540, 'Вневедомственная охрана', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (541, 'Системы сигнализации и охраны', 532, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (542, 'Электроника / Электротехника', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (543, 'Светотехника', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (544, 'Радиоэлектронные приборы', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (545, 'Геодезическое оборудование', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (546, 'Электроустановочная продукция', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (547, 'Ремонт электродвигателей', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (548, 'Кабель / Провод', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (549, 'Электронные компоненты', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (550, 'Элементы питания', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (551, 'Электротехническая продукция', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (552, 'Электронагревательное оборудование', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (553, 'Электродвигатели / Редукторы', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (554, 'Оптические приборы', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (555, 'Контрольно-измерительные приборы (КИПиА)', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (556, 'Электроизоляционные материалы', 542, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (557, 'Текстиль / Предметы интерьера', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (558, 'Керамические изделия', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (559, 'Постельные принадлежности / Текстиль для дома', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (560, 'Ковры', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (561, 'Портьерные ткани / Шторы', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (562, 'Кованые изделия', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (563, 'Пряжа', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (564, 'Карнизы', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (565, 'Нетканые материалы', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (566, 'Жалюзи / Рольставни', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (567, 'Печи / Камины', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (568, 'Швейная фурнитура', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (569, 'Ткани', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (570, 'Интерьерные лестницы / Ограждения', 557, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (571, 'Строительные / отделочные материалы', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (572, 'Фасадные материалы / конструкции', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (573, 'Оргстекло', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (574, 'Заборы / Ограждения', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (575, 'Гидроизоляционные материалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (576, 'Комплектующие для окон', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (577, 'Изготовление художественных витражей / мозаики', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (578, 'Замки / Скобяные изделия', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (579, 'Автоматические ворота / двери', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (580, 'Сэндвич-панели', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (581, 'Стекло / Зеркала', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (582, 'Песок / Щебень', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (583, 'Звукоизоляционные материалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (584, 'Системы перегородок', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (585, 'Лакокрасочные материалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (586, 'Комплектующие для дверей', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (587, 'Декоративные элементы / покрытия', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (588, 'Герметики / Клеи', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (589, 'Пиломатериалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (590, 'Межкомнатные двери', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (591, 'Керамогранит', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (592, 'Керамическая плитка / Кафель', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (593, 'Железобетонные изделия', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (594, 'Сухие строительные смеси', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (595, 'Напольные покрытия / Комплектующие', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (596, 'Огнезащитные материалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (597, 'Обои', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (598, 'Металлоконструкции для строительства зданий / сооружений', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (599, 'Магазины отделочных материалов', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (600, 'Крепежные изделия', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (601, 'Входные двери', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (602, 'Погонажные изделия', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (603, 'Оборудование для производства строительных материалов', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (604, 'Магазины строительных материалов', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (605, 'ДСП / ДВП / Фанера', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (606, 'Гипсокартон / Комплектующие', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (607, 'Бетон / Раствор', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (608, 'Окна', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (609, 'Кирпич / Бетоноблоки / Шлакоблоки', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (610, 'Тротуарная плитка', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (611, 'Теплоизоляционные материалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (612, 'Стеновые / пластиковые панели', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (613, 'Продажа / монтаж потолков', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (614, 'Порошковые краски', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (615, 'Облицовочный камень', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (616, 'Материалы для дорожного строительства', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (617, 'Кровельные материалы', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (618, 'Автоматические ворота "DoorHan"', 571, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (619, 'Одежда / Обувь', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (620, 'Чулочно-носочные изделия', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (621, 'Спецодежда / Средства индивидуальной защиты', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (622, 'Игрушки', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (623, 'Нижнее белье', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (624, 'Детская одежда / обувь', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (625, 'Верхняя одежда', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (626, 'Бижутерия', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (627, 'Спецобувь', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (628, 'Секонд-хенд', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (629, 'Сумки / Кожгалантерея', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (630, 'Мех / Кожа - сырье', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (631, 'Трикотажные изделия', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (632, 'Обувь - опт', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (633, 'Мужская одежда', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (634, 'Сценические / карнавальные костюмы', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (635, 'Ремонт обуви / кожгалантереи', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (636, 'Джинсовая одежда', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (637, 'Товары для новорожденных', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (638, 'Свадебные салоны', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (639, 'Одежда для беременных', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (640, 'Обувная косметика / Аксессуары', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (641, 'Меха / Дубленки / Кожа', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (642, 'Головные уборы', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (643, 'Магазины обувные', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (644, 'Женская одежда', 619, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (645, 'Образование / Работа / Карьера', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (646, 'Профессиональная переподготовка / Повышение квалификации', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (647, 'Обучение творчеству и рукоделию', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (648, 'Обучение бизнес-профессиям', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (649, 'Бухгалтерские курсы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (650, 'Школы иностранных языков', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (651, 'Школы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (652, 'Центры раннего развития / дошкольного образования детей', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (653, 'Университеты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (654, 'Лицеи-интернаты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (655, 'Лицеи', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (656, 'Автошколы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (657, 'Техникумы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (658, 'Обучение сотрудников охраны', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (659, 'Обучение за рубежом', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (660, 'Научно-исследовательские институты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (661, 'Школы-интернаты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (662, 'Помощь в обучении', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (663, 'Обучение косметологов', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (664, 'Начальные школы-детские сады / Прогимназии', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (665, 'Институты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (666, 'Личностные тренинги / семинары', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (667, 'Кадровые / рекрутинговые агентства', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (668, 'Обучение мастеров для салонов красоты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (669, 'Музыкальные школы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (670, 'Компьютерные курсы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (671, 'Художественные школы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (672, 'Профессиональные лицеи', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (673, 'Обучение рабочим профессиям', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (674, 'Обучение по охране труда', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (675, 'Дизайнерские курсы', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (676, 'Гимназии-интернаты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (677, 'Школы искусств', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (678, 'Перевод с иностранных языков', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (679, 'Межшкольные учебные комбинаты', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (680, 'Колледжи', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (681, 'Бизнес-тренинги / семинары', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (682, 'Училища', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (683, 'Конструкторские бюро', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (684, 'Академии', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (685, 'Агентства по трудоустройству за рубежом', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (686, 'Гимназии', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (687, 'Детские сады / Ясли', 645, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (688, 'Мебель / Материалы / Фурнитура', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (689, 'Плетеная мебель / изделия', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (690, 'Мебель для учебных и дошкольных учреждений', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (691, 'Детская мебель', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (692, 'Мебель для ванных комнат', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (693, 'Мебель из стекла', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (694, 'Матрасы', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (695, 'Изготовление мебели под заказ', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (696, 'Бескаркасная мебель', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (697, 'Сейфы', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (698, 'Мебель для кухни', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (699, 'Серийное производство мебели', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (700, 'Мебель мягкая', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (701, 'Мебель для предприятий общественного питания', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (702, 'ЛДСП / ДВПО / МДФ', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (703, 'Изделия из камня для помещений', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (704, 'Мебельные фасады', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (705, 'Мебель офисная', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (706, 'Облицовочные материалы для мебели', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (707, 'Мебель корпусная', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (708, 'Мебель для медицинских учреждений и лабораторий', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (709, 'Мебельные ткани', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (710, 'Садово-парковая мебель / Аксессуары', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (711, 'Металлическая мебель для помещений', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (712, 'Мебельная фурнитура', 688, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (713, 'Культура / Искусство / Религия', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (714, 'Планетарий', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (715, 'Киностудии', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (716, 'Библиотеки', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (717, 'Художественные салоны', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (718, 'Религиозные товары', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (719, 'Воскресные школы', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (720, 'Антиквариат', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (721, 'Художественные мастерские', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (722, 'Филармония', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (723, 'Продажа театральных билетов', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (724, 'Религиозные организации', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (725, 'Мечети', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (726, 'Художественные выставки / Галереи', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (727, 'Музеи', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (728, 'Городские оркестры', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (729, 'Храмы / Соборы / Церкви', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (730, 'Театры', 713, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (731, 'Металлы / Топливо / Химия', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (732, 'Технические газы / Криогенные жидкости', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (733, 'Прием / переработка металла', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (734, 'Уголь', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (735, 'Сварочные материалы', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (736, 'Производство изделий из пластмасс', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (737, 'Металлоизделия', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (738, 'Геологоразведочные работы', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (739, 'Металлообработка', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (740, 'Утилизация отходов / Вторсырье', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (741, 'Цветной металлопрокат', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (742, 'Промышленная химия / Химическое сырье', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (743, 'Нержавеющий металлопрокат', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (744, 'Нефтепродукты / ГСМ / Газ', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (745, 'Черный металлопрокат', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (746, 'Красящие вещества', 731, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (747, 'Компьютеры / Бытовая техника / Офисная техника', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (748, 'Сетевое оборудование', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (749, 'Оргтехника', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (750, 'Фототовары', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (751, 'Ремонт бытовой техники', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (752, 'Услуги системного администрирования', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (753, 'Ремонт аудио / видео / цифровой техники', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (754, 'Продажа кулеров для воды', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (755, 'Модернизация компьютеров', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (756, 'Компьютеры / Комплектующие', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (757, 'Ремонт оргтехники', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (758, 'Музыкальные инструменты / Аксессуары', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (759, 'Бытовая техника', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (760, 'Аудио- / видеотехника', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (761, 'CD / DVD / BD', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (762, 'Ремонт компьютеров', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (763, 'Заправка картриджей', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (764, 'Расходные материалы для оргтехники', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (765, 'Монтаж компьютерных сетей', 747, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (766, 'Город / Власть', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (767, 'Посольства / Консульства', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (768, 'Государственные архивы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (769, 'ГИБДД', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (770, 'Администрация сельских поселений', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (771, 'Службы судебных приставов', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (772, 'Правительство Республики Башкортостан', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (773, 'Организации природоохраны', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (774, 'Дома ребенка', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (775, 'Гидрометеослужба', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (776, 'Администрация городского округа города Уфы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (777, 'Федеральные службы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (778, 'Социальные службы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (779, 'Прокуратура', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (780, 'Избирательные комиссии', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (781, 'Детские дома / Приюты', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (782, 'Участковые пункты милиции', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (783, 'Органы государственного надзора', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (784, 'ЗАГСы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (785, 'Администрация Президента Республики Башкортостан', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (786, 'Федеральные казначейства', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (787, 'Политические организации', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (788, 'Исправительные учреждения', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (789, 'Законодательная власть', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (790, 'Суды', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (791, 'Судебная экспертиза', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (792, 'РУВД / Отделения милиции', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (793, 'Пенсионные фонды', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (794, 'Налоговые инспекции', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (795, 'УВД / ГУВД / МВД', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (796, 'Службы занятости населения', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (797, 'Фонды социального страхования', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (798, 'Фонд обязательного медицинского страхования', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (799, 'Таможня', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (800, 'Изоляторы временного содержания', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (801, 'Отделы ветеринарно-санитарного контроля', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (802, 'Дома престарелых', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (803, 'Военкоматы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (804, 'Благотворительные фонды', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (805, 'Федеральные миграционные службы', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (806, 'Следственный комитет', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (807, 'Общественные организации', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (808, 'Военная комендатура', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (809, 'Инспекции', 766, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (810, 'Продукты питания / Напитки', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (811, 'Хлебобулочные изделия', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (812, 'Мука / Крупы', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (813, 'Колбасные изделия', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (814, 'Киоски фастфудной продукции', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (815, 'Зернопереработка', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (816, 'Рыба / Морепродукты', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (817, 'Мороженое', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (818, 'Чай / Кофе', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (819, 'Продукты пчеловодства', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (820, 'Кондитерские изделия', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (821, 'Яйцо', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (822, 'Орехи / Семечки', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (823, 'Жир / Маслопродукты', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (824, 'Диетические / Соевые продукты', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (825, 'Алкогольные напитки', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (826, 'Сахар / Соль', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (827, 'Овощи / Фрукты / Ягоды / Грибы', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (828, 'Молочные продукты', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (829, 'Специи / Пряности', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (830, 'Продовольственные магазины', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (831, 'Пиво', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (832, 'Мясо / Полуфабрикаты', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (833, 'Зерно / Зерноотходы', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (834, 'Мясо птицы / Полуфабрикаты', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (835, 'Сырье для пищевой промышленности', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (836, 'Сыры', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (837, 'Продажа / доставка питьевой воды', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (838, 'Макаронные изделия', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (839, 'Консервированная продукция', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (840, 'Детское питание', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (841, 'Безалкогольные напитки', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (842, 'Табачные изделия / Товары для курения', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (843, 'Снэковая продукция', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (844, 'Продукты быстрого приготовления', 810, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (845, 'Интернет / Связь / Информационные технологии', NULL, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (846, 'Государственные информационные сайты', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (847, 'Автоматизация производственных процессов', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (848, 'Строительство / проектирование объектов связи', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (849, 'Операторы сотовой связи', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (850, 'Правовые программы', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (851, 'Операторы кабельного телевидения', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (852, 'Интернет-провайдеры', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (853, 'Бюро ремонта городских АТС', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (854, 'Автоматизация торговли', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (855, 'Разработка / поддержка / продвижение web-сайтов', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (856, 'Почтовые отделения', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (857, 'Поисковые интернет-системы', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (858, 'Монтаж / обслуживание антенного оборудования', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (859, 'IP-телефония', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (860, 'Монтаж телефонных сетей', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (861, 'Мобильные телефоны', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (862, 'Коммутационное оборудование', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (863, 'Автоматизация бизнес-процессов', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (864, 'Хостинг', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (865, 'Телефоны / Радиотелефоны', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (866, 'Спутниковая связь', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (867, 'Навигационное оборудование', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (868, 'Средства радиосвязи', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (869, 'Ремонт мобильных устройств связи', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (870, 'Продажа электронных цифровых подписей', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (871, 'Офисные АТС', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (872, 'Компьютерные клубы', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (873, 'Городские информационные сайты', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (874, 'Бухгалтерские программы', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (875, 'Антенное оборудование', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (876, 'Услуги телефонной связи', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (877, 'Информационная безопасность', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (878, 'Аксессуары к мобильным телефонам', 845, '');
INSERT INTO info_category (id, name, parent_id, key_words) VALUES (879, 'Продажа программного обеспечения', 845, '');